baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: Jidin Dinesh
theme: cupper-hugo-theme
#googleAnalytics: 
#disqusShortname:
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Hi, I'm Jidin DineshğŸ‘‹.  
  footer: ğŸ“§ [Email](mailto:jidin@pm.me) ğŸ¦ [Twitter](https://twitter.com/JidinDinesh)
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: false
  moveFooterToHeader: true	
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu: 
  nav:
   - name: ğŸ“œ Blog
     url: /post/
     weight: 1
   - name: ğŸ— Newsletter
     url: https://newsletter.jidin.co
     weight: 2
   - name: ğŸ“¸ Photography
     url: /photos/
     weight: 3
   - name: ğŸ’» Code
     url: https://gitlab.com/jidin
     weight: 4


    # - name: Topics      url: /tags/      
   #- name: RSS url: /index.xml 

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 10
    startLevel: 1
